ARG PYTHON_VERSION=3.10.2

FROM flink:1.17.2-java11
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python3 -m pip install -r requirements.txt

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY . .
CMD python3 flink_pipeline_main.py
