apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: conformance-metrics-podmonitor
  labels:
    app: theodolite
spec:
  selector:
    matchLabels:
      app: conformance-metrics
  podMetricsEndpoints:
    - path: /metrics
      port: metric