apiVersion: v1
kind: Service
metadata:
  name: conformance-metrics
  labels:
    app: conformance-metrics
spec:
  type: NodePort
  ports:
    - name: metric
      port: 5000
      targetPort: 5000
  selector:
    app: conformance-metrics